// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "staffinc/internal/model/entity"

	mock "github.com/stretchr/testify/mock"

	repository "staffinc/internal/repository"
)

// UserRepoProvider is an autogenerated mock type for the UserRepoProvider type
type UserRepoProvider struct {
	mock.Mock
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepoProvider) FindUserByEmail(ctx context.Context, email string) (entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUser provides a mock function with given fields: ctx, tx, user
func (_m *UserRepoProvider) InsertUser(ctx context.Context, tx repository.TxProvider, user entity.User) (int64, error) {
	ret := _m.Called(ctx, tx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.TxProvider, entity.User) (int64, error)); ok {
		return rf(ctx, tx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.TxProvider, entity.User) int64); ok {
		r0 = rf(ctx, tx, user)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.TxProvider, entity.User) error); ok {
		r1 = rf(ctx, tx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepoProvider creates a new instance of UserRepoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepoProvider {
	mock := &UserRepoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
