basePath: /api
definitions:
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  response.GenericResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  response.LoginResponse:
    properties:
      data:
        $ref: '#/definitions/response.TokenResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
  response.TokenResponse:
    properties:
      token:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: 'Register, PIC : Irfan Fauzi'
      operationId: v1-LoginApiHandler
      parameters:
      - description: LoginRequest
        in: body
        name: RegisterRequest
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GenericResponse'
      summary: LoginApiHandler
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: 'Register, PIC : Irfan Fauzi'
      operationId: v1-RegisterApiHandler
      parameters:
      - description: RegisterRequest
        in: body
        name: RegisterRequest
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.GenericResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GenericResponse'
      summary: RegisterApiHandler
      tags:
      - Auth
  /generic-response:
    post:
      consumes:
      - application/json
      description: 'Register, PIC : Irfan Fauzi'
      operationId: v1-PostGenerateLinkHandler
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.GenericResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GenericResponse'
      summary: PostGenerateLinkHandler
      tags:
      - Generate Link
swagger: "2.0"
